apiVersion: v1
kind: Service
metadata:
  name: user-ctseapp-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: user-ctseapp-k8
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
